"""Tools for automatic plotting with ``pyqtgraph``.

Contains a ``pyqtgraph``-specific implementation of :class:`.plot.base.FigureMaker`
(:class:`.FigureMaker`) and :class:`.plot.base.PlotWidget` (:class:`.AutoPlot`).
``FigureMaker`` can be used to quickly create a figure in a mostly automatic fashion
from known data.
For embedding in GUIs (such as plottr applications), ``AutoPlot`` is the main
object for plotting data automatically using ``pyqtgraph``.
"""

import logging
from pathlib import Path
import time
from dataclasses import dataclass
from typing import List, Optional, Any

import numpy as np
from pyqtgraph import mkPen

from plottr import QtWidgets, QtCore, Signal, Slot, \
    config_entry as getcfg
from plottr.data.datadict import DataDictBase
from .plots import Plot, PlotWithColorbar, PlotBase
from ..base import AutoFigureMaker as BaseFM, PlotDataType, \
    PlotItem, ComplexRepresentation, determinePlotDataType, \
    PlotWidgetContainer, PlotWidget

logger = logging.getLogger(__name__)

TIMESTRFORMAT = "%Y-%m-%dT%H%M%S"


class FigureWidget(QtWidgets.QWidget):
    """Widget that contains all plots generated by :class:`.FigureMaker`.

    Widget has a grid layout. Plots are filled row-wise with up to a
    configurable number of columns.
    """

    def __init__(self, parent: Optional[QtWidgets.QWidget] = None):
        """Constructor for :class:`.FigureMakerWidget`.

        :param parent: parent widget.
        """
        super().__init__(parent=parent)

        self.subPlots: List[PlotBase] = []

        self.title = QtWidgets.QLabel(parent=self)
        self.title.setAlignment(QtCore.Qt.AlignHCenter)

        self.gridContainer = QtWidgets.QWidget(parent=self)
        self.gridContainer.setSizePolicy(QtWidgets.QSizePolicy.Expanding,
                         QtWidgets.QSizePolicy.Expanding)
        self.gridLayout = QtWidgets.QGridLayout(self.gridContainer)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)

        layout = QtWidgets.QVBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(2)
        layout.addWidget(self.title)
        layout.addWidget(self.gridContainer, 1)
        self.setLayout(layout)

        self.setTitle('')

    def addPlot(self, plot: PlotBase) -> None:
        """Add a :class:`.PlotBase` widget.

        :param plot: plot widget
        :param title: title of the plot
        """
        max_cols = int(getcfg('main', 'pyqtgraph', 'subplot_max_columns', default=3))
        max_cols = max(1, min(3, max_cols))
        idx = len(self.subPlots)
        row = idx // max_cols
        col = idx % max_cols
        self.gridLayout.addWidget(plot, row, col)
        self.subPlots.append(plot)

    def clearAllPlots(self) -> None:
        """Clear all plot contents."""
        for p in self.subPlots:
            p.clearPlot()

    def deleteAllPlots(self) -> None:
        """Delete all subplot widgets."""
        for p in self.subPlots:
            self.gridLayout.removeWidget(p)
            p.deleteLater()
        self.subPlots = []

    def setTitle(self, title: str = '') -> None:
        self.title.setText(title)
        if len(title.strip()) == 0:
            self.title.setVisible(False)
        else:
            self.title.setVisible(True)


class FigureMaker(BaseFM):
    """``pyqtgraph`` implementation for :class:`.AutoFigureMaker`.

    Please see the base class for more general information.
    """

    # TODO: make scrollable when many figures (set min size)?
    # TODO: check for valid plot data

    def __init__(self, widget: Optional[FigureWidget] = None,
                 clearWidget: bool = True,
                 parentWidget: Optional[QtWidgets.QWidget] = None):
        """Constructor for :class:`.FigureMaker`.

        :param widget: a widget produced by an earlier use of this class
            may be supplied. This widget will then be used for generating the
            plot and avoids deleting and re-creating the widget if no structural
            changes to the plots is required (important case is live-plotting of
            data that keeps updating).
        :param clearWidget:
            if ``True`` force re-creation of all plot elements.
        :param parentWidget:
            parent of the main widget of FigureMaker.
        """
        super().__init__()

        self.widget: FigureWidget
        self.clearWidget = clearWidget

        if widget is None:
            self.widget = FigureWidget(parent=parentWidget)
        else:
            self.widget = widget

        self.colormap = getcfg('main', 'pyqtgraph', 'default_colormap', default='magma_r')
        self.logX = False
        self.logY = False
        self.logColor = False
        self.fftAxis = 'none'

    # re-implementing to get correct type annotation.
    def __enter__(self) -> "FigureMaker":
        return self

    def subPlotFromId(self, subPlotId: int) -> PlotBase:
        """Get SubPlot from ID."""
        subPlots = self.subPlots[subPlotId].axes
        assert isinstance(subPlots, list) and len(subPlots) > 0 and \
               isinstance(subPlots[0], PlotBase)
        return subPlots[0]

    def makeSubPlots(self, nSubPlots: int) -> List[PlotBase]:
        """Create empty subplots in the widgets.

        If ``clearWidget`` was not set to ``True`` in the constructor,
        existing sub plot widgets are cleared, but not deleted and re-created.
        """
        plot: PlotBase
        if self.clearWidget:
            self.widget.deleteAllPlots()
            for i in range(nSubPlots):
                if max(self.dataDimensionsInSubPlot(i).values()) == 1:
                    plot = Plot(self.widget)
                    self.widget.addPlot(plot)
                elif max(self.dataDimensionsInSubPlot(i).values()) == 2:
                    plot = PlotWithColorbar(self.widget)
                    self.widget.addPlot(plot)
        else:
            self.widget.clearAllPlots()

        return self.widget.subPlots

    def formatSubPlot(self, subPlotId: int) -> None:
        """Set labels/legends for the given subplot."""
        if len(self.plotIdsInSubPlot(subPlotId)) == 0:
            return

        labels = self.subPlotLabels(subPlotId)
        subPlot = self.subPlotFromId(subPlotId)

        # label the x axis if there's only one x label
        if isinstance(subPlot, Plot):
            if len(set(labels[0])) == 1:
                subPlot.plot.setLabel("bottom", labels[0][0])

        if isinstance(subPlot, PlotWithColorbar):
            subPlot.setColormap(self.colormap)
            if len(set(labels[0])) == 1:
                subPlot.plot.setLabel("bottom", labels[0][0])

            if len(set(labels[1])) == 1:
                subPlot.plot.setLabel('left', labels[1][0])

            if len(set(labels[2])) == 1:
                subPlot.colorbar.setLabel('left', labels[2][0])

        # Apply FFT labels last so they are not overwritten by default labels.
        if self.fftAxis in ['x', 'y']:
            if isinstance(subPlot, PlotWithColorbar):
                if self.fftAxis == 'x' and len(set(labels[0])) == 1:
                    subPlot.plot.setLabel('bottom', f'FFT freq({labels[0][0]})')
                if self.fftAxis == 'y' and len(set(labels[1])) == 1:
                    subPlot.plot.setLabel('left', f'FFT freq({labels[1][0]})')
                if len(set(labels[2])) == 1:
                    subPlot.colorbar.setLabel('left', f'|FFT({labels[2][0]})|')
            elif isinstance(subPlot, Plot):
                if len(set(labels[0])) == 1:
                    subPlot.plot.setLabel('bottom', f'FFT freq({labels[0][0]})')
                if len(set(labels[1])) == 1:
                    subPlot.plot.setLabel('left', f'|FFT({labels[1][0]})|')

    def plot(self, plotItem: PlotItem) -> None:
        """Plot the given item."""
        if plotItem.plotDataType is PlotDataType.unknown:
            if len(plotItem.data) == 2:
                plotItem.plotDataType = PlotDataType.scatter1d
            elif len(plotItem.data) == 3:
                plotItem.plotDataType = PlotDataType.scatter2d
        
        #If the Complex Representation is LogMag
        if self.complexRepresentation == ComplexRepresentation.log_MagAndPhase:

            #Switch the 1d plots to the logarithmic variation if the plot is the Magnitude plot (not the Phase Plot)
            if plotItem.subPlot == 0:
                if plotItem.plotDataType == PlotDataType.scatter1d: plotItem.plotDataType = PlotDataType.log10_scatter1d
                if plotItem.plotDataType == PlotDataType.line1d: plotItem.plotDataType = PlotDataType.log10_line1d
        
        if plotItem.plotDataType in [PlotDataType.scatter1d, PlotDataType.line1d,PlotDataType.log10_line1d,PlotDataType.log10_scatter1d]:
            self._1dPlot(plotItem)
        elif plotItem.plotDataType == PlotDataType.grid2d:
            self._colorPlot(plotItem)
        elif plotItem.plotDataType == PlotDataType.scatter2d:
            self._scatterPlot2d(plotItem)
        else:
            raise NotImplementedError('Cannot plot this data.')

    def _1dPlot(self, plotItem: PlotItem) -> None:
        colors = getcfg('main', 'pyqtgraph', 'line_colors', default=['r', 'b', 'g'])
        symbols = getcfg('main', 'pyqtgraph', 'line_symbols', default=['o'])
        symbolSize = getcfg('main', 'pyqtgraph', 'line_symbol_size', default=5)
        max_line_points = getcfg('main', 'pyqtgraph', 'adaptive_1d_max_points', default=200000)
        max_scatter_points = getcfg('main', 'pyqtgraph', 'adaptive_scatter_max_points', default=80000)

        subPlot = self.subPlotFromId(plotItem.subPlot)

        assert len(plotItem.data) == 2
        x, y = plotItem.data


        color = colors[self.findPlotIndexInSubPlot(plotItem.id) % len(colors)]
        symbol = symbols[self.findPlotIndexInSubPlot(plotItem.id) % len(symbols)]
        if isinstance(plotItem.labels, list):
             name = plotItem.labels[-1]
        else:
            name = ''

        # flatten and apply data transformations (if applicable)
        x = x.flatten()
        y = y.flatten()
        if plotItem.plotDataType in [PlotDataType.log10_line1d, PlotDataType.log10_scatter1d]:
            # Use dB scaling based on log10 of magnitude (NumPy-safe for complex values).
            y = 20 * self._safeLog10(y)

        if self.fftAxis in ['x', 'y']:
            x, y = self._fft1d(x, y)
            x_label = subPlot.plot.getAxis('bottom').labelText or 'x'
            y_label = subPlot.plot.getAxis('left').labelText or 'y'
            subPlot.plot.setLabel('bottom', f'FFT freq({x_label})')
            subPlot.plot.setLabel('left', f'|FFT({y_label})|')

        if self.logX:
            mask = x > 0
            x = x[mask]
            y = y[mask]
        if self.logY:
            mask = y > 0
            x = x[mask]
            y = y[mask]

        subPlot.plot.setLogMode(x=self.logX, y=self.logY)

        if x.size > max_line_points:
            stride = int(np.ceil(x.size / max_line_points))
            x = x[::stride]
            y = y[::stride]

        # Use explicit finite ranges for robust autoscaling across pyqtgraph versions.
        finite = np.isfinite(x) & np.isfinite(y)
        x_rng = None
        y_rng = None
        if np.any(finite):
            xf = x[finite]
            yf = y[finite]
            x_rng = (float(np.min(xf)), float(np.max(xf)))
            y_rng = (float(np.min(yf)), float(np.max(yf)))

        #plot either line or scatter depending on what graph is being requested
        if plotItem.plotDataType in [PlotDataType.line1d, PlotDataType.log10_line1d]:
            curve = subPlot.plot.plot(x, y, name=name,
                                      pen=mkPen(color, width=1), symbol=symbol, symbolBrush=color,
                                      symbolPen=None, symbolSize=symbolSize)
            curve.setClipToView(True)
            curve.setDownsampling(auto=True, method='peak')
            subPlot.plot.enableAutoRange(axis='xy', enable=True)
            subPlot.plot.autoRange()
            if x_rng is not None and y_rng is not None:
                subPlot.plot.setXRange(*x_rng, padding=0.03)
                subPlot.plot.setYRange(*y_rng, padding=0.06)
            return curve
        else: #plotItem.plotDataType is either PlotDataType.scatter1d or PlotDataType.log10_scatter1d
            if x.size > max_scatter_points:
                stride = int(np.ceil(x.size / max_scatter_points))
                x = x[::stride]
                y = y[::stride]
            curve = subPlot.plot.plot(x, y, name=name,
                                      pen=None, symbol=symbol, symbolBrush=color,
                                      symbolPen=None, symbolSize=symbolSize)
            subPlot.plot.enableAutoRange(axis='xy', enable=True)
            subPlot.plot.autoRange()
            if x_rng is not None and y_rng is not None:
                subPlot.plot.setXRange(*x_rng, padding=0.03)
                subPlot.plot.setYRange(*y_rng, padding=0.06)
            return curve

    def _colorPlot(self, plotItem: PlotItem) -> None:
        subPlot = self.subPlotFromId(plotItem.subPlot)
        assert isinstance(subPlot, PlotWithColorbar) and len(plotItem.data) == 3
        x, y, z = plotItem.data
        x = np.asarray(x)
        y = np.asarray(y)
        z = np.asarray(z)

        x, y, z = self._normalize_grid_axis_order(x, y, z)

        if self.fftAxis == 'x':
            x, z = self._fft2d_axis_x(x, z)
            x_label = subPlot.plot.getAxis('bottom').labelText or 'x'
            z_label = subPlot.colorbar.axis.labelText or 'z'
            subPlot.plot.setLabel('bottom', f'FFT freq({x_label})')
            subPlot.colorbar.setLabel('left', f'|FFT({z_label})|')
        elif self.fftAxis == 'y':
            y, z = self._fft2d_axis_y(y, z)
            y_label = subPlot.plot.getAxis('left').labelText or 'y'
            z_label = subPlot.colorbar.axis.labelText or 'z'
            subPlot.plot.setLabel('left', f'FFT freq({y_label})')
            subPlot.colorbar.setLabel('left', f'|FFT({z_label})|')

        if self.logColor:
            z = self._safeLog10(z)

        if self.logX:
            x, y, z = self._transform2d_for_log_x(x, y, z)
        if self.logY:
            x, y, z = self._transform2d_for_log_y(x, y, z)

        if z.size == 0:
            return

        subPlot.setColormap(self.colormap)
        subPlot.plot.setLogMode(x=False, y=False)
        subPlot.setImage(x, y, z)

    def _normalize_grid_axis_order(self, x: np.ndarray, y: np.ndarray, z: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Ensure displayed 2D grids are ordered with ascending x/y axes.

        Acquisition order can be descending on either axis. Reorder data and
        coordinates so the displayed image orientation is consistent.
        """
        x_arr = np.asarray(x)
        y_arr = np.asarray(y)
        z_arr = np.asarray(z)

        if z_arr.ndim != 2:
            return x_arr, y_arr, z_arr

        ny, nx = z_arr.shape

        def _varying_axis_and_vector(arr: np.ndarray) -> tuple[Optional[int], Optional[np.ndarray]]:
            """Return which z-axis the coordinate varies along and its 1D vector.

            Returns:
            - axis 0 with vector length ny when coordinate varies by rows
            - axis 1 with vector length nx when coordinate varies by columns
            - (None, None) if not enough information
            """
            if arr.ndim == 1:
                if arr.size == ny:
                    return 0, np.asarray(arr, dtype=float)
                if arr.size == nx:
                    return 1, np.asarray(arr, dtype=float)
                return None, None

            if arr.ndim == 2 and arr.shape == z_arr.shape:
                with np.errstate(invalid='ignore'):
                    d0 = np.nanmedian(np.abs(np.diff(arr, axis=0)))
                    d1 = np.nanmedian(np.abs(np.diff(arr, axis=1)))

                if np.isfinite(d0) and (not np.isfinite(d1) or d0 > d1):
                    return 0, np.asarray(np.nanmedian(arr, axis=1), dtype=float)
                if np.isfinite(d1):
                    return 1, np.asarray(np.nanmedian(arr, axis=0), dtype=float)

            return None, None

        def _stable_sort_idx(vec: np.ndarray) -> Optional[np.ndarray]:
            finite = np.isfinite(vec)
            if np.count_nonzero(finite) < 2:
                return None
            fill = np.nanmax(vec[finite]) + 1.0
            sort_vec = np.where(finite, vec, fill)
            return np.argsort(sort_vec)

        x_var_axis, x_vec = _varying_axis_and_vector(x_arr)
        if x_vec is not None and x_var_axis is not None:
            x_idx = _stable_sort_idx(x_vec)
            if x_idx is not None:
                if x_var_axis == 0:
                    z_arr = z_arr[x_idx, :]
                    if x_arr.ndim == 2 and x_arr.shape == z_arr.shape:
                        x_arr = x_arr[x_idx, :]
                    else:
                        x_arr = x_arr[x_idx]
                    if y_arr.ndim == 2 and y_arr.shape == z_arr.shape:
                        y_arr = y_arr[x_idx, :]
                else:
                    z_arr = z_arr[:, x_idx]
                    if x_arr.ndim == 2 and x_arr.shape == z_arr.shape:
                        x_arr = x_arr[:, x_idx]
                    else:
                        x_arr = x_arr[x_idx]
                    if y_arr.ndim == 2 and y_arr.shape == z_arr.shape:
                        y_arr = y_arr[:, x_idx]

        y_var_axis, y_vec = _varying_axis_and_vector(y_arr)
        if y_vec is not None and y_var_axis is not None:
            y_idx = _stable_sort_idx(y_vec)
            if y_idx is not None:
                if y_var_axis == 0:
                    z_arr = z_arr[y_idx, :]
                    if y_arr.ndim == 2 and y_arr.shape == z_arr.shape:
                        y_arr = y_arr[y_idx, :]
                    else:
                        y_arr = y_arr[y_idx]
                    if x_arr.ndim == 2 and x_arr.shape == z_arr.shape:
                        x_arr = x_arr[y_idx, :]
                else:
                    z_arr = z_arr[:, y_idx]
                    if y_arr.ndim == 2 and y_arr.shape == z_arr.shape:
                        y_arr = y_arr[:, y_idx]
                    else:
                        y_arr = y_arr[y_idx]
                    if x_arr.ndim == 2 and x_arr.shape == z_arr.shape:
                        x_arr = x_arr[:, y_idx]

        return x_arr, y_arr, z_arr

    def _scatterPlot2d(self, plotItem: PlotItem) -> None:
        subPlot = self.subPlotFromId(plotItem.subPlot)
        assert isinstance(subPlot, PlotWithColorbar) and len(plotItem.data) == 3
        assert not self.complexRepresentation == ComplexRepresentation.log_MagAndPhase
        x, y, z = plotItem.data

        x = np.asarray(x, dtype=float)
        y = np.asarray(y, dtype=float)
        z = np.asarray(z)

        if self.fftAxis in ['x', 'y']:
            x_flat, y_flat, z_flat = self._fft_scatter2d(x, y, z, axis=self.fftAxis)
            if x_flat.size == 0:
                return
            x = x_flat
            y = y_flat
            z = z_flat

            z_label = subPlot.colorbar.axis.labelText or 'z'
            if self.fftAxis == 'x':
                x_label = subPlot.plot.getAxis('bottom').labelText or 'x'
                subPlot.plot.setLabel('bottom', f'FFT freq({x_label})')
            else:
                y_label = subPlot.plot.getAxis('left').labelText or 'y'
                subPlot.plot.setLabel('left', f'FFT freq({y_label})')
            subPlot.colorbar.setLabel('left', f'|FFT({z_label})|')

        finite_mask = np.isfinite(x) & np.isfinite(y)
        if self.logX:
            finite_mask &= x > 0
            x = np.log10(x, where=(x > 0), out=np.full_like(x, np.nan))
        if self.logY:
            finite_mask &= y > 0
            y = np.log10(y, where=(y > 0), out=np.full_like(y, np.nan))

        if self.logColor:
            z = self._safeLog10(np.asarray(z))

        z = np.asarray(z)
        finite_mask &= np.isfinite(z)
        if np.any(finite_mask):
            x = x[finite_mask]
            y = y[finite_mask]
            z = z[finite_mask]
        else:
            return

        subPlot.setColormap(self.colormap)
        subPlot.plot.setLogMode(x=False, y=False)
        subPlot.setScatter2d(x, y, z)

    def _safeLog10(self, vals: np.ndarray) -> np.ndarray:
        arr = np.asarray(vals)
        if np.iscomplexobj(arr):
            arr = np.abs(arr)
        out = np.full(arr.shape, np.nan, dtype=float)
        mask = arr > 0
        if np.any(mask):
            out[mask] = np.log10(arr[mask])
        else:
            out[:] = 0.0
        return out

    def _transform2d_for_log_x(self, x: np.ndarray, y: np.ndarray, z: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        if x.ndim == 2:
            axis = x[0, :]
            mask = axis > 0
            if not np.any(mask):
                return x[:, :0], y[:, :0], z[:, :0]
            x = np.log10(x[:, mask])
            y = y[:, mask]
            z = z[:, mask]
            return x, y, z

        mask = x > 0
        if not np.any(mask):
            return x[:0], y[:0], z[:0]
        x = np.log10(x[mask])
        if y.ndim == 2:
            y = y[:, mask]
        z = z[:, mask] if z.ndim == 2 else z[mask]
        return x, y, z

    def _transform2d_for_log_y(self, x: np.ndarray, y: np.ndarray, z: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        if y.ndim == 2:
            axis = y[:, 0]
            mask = axis > 0
            if not np.any(mask):
                return x[:0, :], y[:0, :], z[:0, :]
            y = np.log10(y[mask, :])
            x = x[mask, :]
            z = z[mask, :]
            return x, y, z

        mask = y > 0
        if not np.any(mask):
            return x[:0], y[:0], z[:0]
        y = np.log10(y[mask])
        if x.ndim == 2:
            x = x[mask, :]
        z = z[mask, :] if z.ndim == 2 else z[mask]
        return x, y, z

    def _fft1d(self, x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        xv = np.asarray(x)
        yv = np.asarray(y)
        if xv.size < 2:
            return xv, yv
        order = np.argsort(xv)
        xv = xv[order]
        yv = yv[order]
        diffs = np.diff(xv)
        diffs = diffs[np.isfinite(diffs) & (diffs != 0)]
        if diffs.size == 0:
            return xv, yv
        dx = float(np.median(np.abs(diffs)))
        if dx == 0:
            return xv, yv
        xf, yf = self._fft_positive_frequency(yv, abs(dx))
        return xf, yf

    def _fft_positive_frequency(self, values: np.ndarray, spacing: float) -> tuple[np.ndarray, np.ndarray]:
        vals = np.asarray(values, dtype=float)
        if vals.size < 2 or spacing <= 0:
            return np.array([]), np.array([])

        finite = np.isfinite(vals)
        if not np.any(finite):
            return np.array([]), np.array([])
        if np.count_nonzero(finite) < vals.size:
            fill = float(np.nanmean(vals[finite]))
            vals = vals.copy()
            vals[~finite] = fill

        remove_dc = bool(getcfg('main', 'pyqtgraph', 'fft_remove_dc', default=True))
        detrend_linear = bool(getcfg('main', 'pyqtgraph', 'fft_detrend_linear', default=True))
        apply_window = bool(getcfg('main', 'pyqtgraph', 'fft_apply_hann_window', default=True))
        drop_zero = bool(getcfg('main', 'pyqtgraph', 'fft_drop_zero_bin', default=True))
        drop_low_bins = int(getcfg('main', 'pyqtgraph', 'fft_drop_low_bins', default=2))

        if remove_dc:
            vals = vals - float(np.mean(vals))

        if detrend_linear and vals.size > 1:
            idx = np.arange(vals.size, dtype=float)
            slope = (vals[-1] - vals[0]) / float(vals.size - 1)
            vals = vals - (vals[0] + slope * idx)

        if apply_window and vals.size > 1:
            vals = vals * np.hanning(vals.size)

        freqs = np.fft.rfftfreq(vals.size, d=spacing)
        fft_vals = np.fft.rfft(vals)
        amps = np.abs(fft_vals)

        if drop_zero and freqs.size > 1:
            freqs = freqs[1:]
            amps = amps[1:]

        if drop_low_bins > 0 and freqs.size > drop_low_bins:
            freqs = freqs[drop_low_bins:]
            amps = amps[drop_low_bins:]

        return freqs, amps

    def _fft2d_axis_x(self, x: np.ndarray, z: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        if z.ndim != 2 or max(z.shape) < 2:
            return x, z

        zf_in = np.asarray(z, dtype=float)
        fft_axis = 1
        if x.ndim == 2 and x.shape == z.shape:
            with np.errstate(invalid='ignore'):
                dx1 = np.nanmedian(np.abs(np.diff(x, axis=1)))
                dx0 = np.nanmedian(np.abs(np.diff(x, axis=0)))
            if np.isfinite(dx1) and (not np.isfinite(dx0) or dx1 >= dx0):
                fft_axis = 1
                x_axis = np.nanmedian(x, axis=0)
            else:
                fft_axis = 0
                x_axis = np.nanmedian(x, axis=1)
        elif x.ndim == 1 and x.size == z.shape[1]:
            fft_axis = 1
            x_axis = x
        elif x.ndim == 1 and x.size == z.shape[0]:
            fft_axis = 0
            x_axis = x
        else:
            return x, z

        finite_coord = np.isfinite(x_axis)
        if np.count_nonzero(finite_coord) < 2:
            return x, z
        x_axis = x_axis[finite_coord]
        if fft_axis == 1:
            zf_in = zf_in[:, finite_coord]
        else:
            zf_in = zf_in[finite_coord, :]

        sort_idx = np.argsort(x_axis)
        x_axis = x_axis[sort_idx]
        if fft_axis == 1:
            zf_in = zf_in[:, sort_idx]
        else:
            zf_in = zf_in[sort_idx, :]
        diffs = np.diff(x_axis)
        diffs = diffs[np.isfinite(diffs) & (diffs != 0)]
        if diffs.size == 0:
            return x, z
        dx = float(np.median(np.abs(diffs)))
        if dx == 0:
            return x, z

        # Replace NaNs per trace to keep FFT numerically meaningful.
        if fft_axis == 1:
            for r in range(zf_in.shape[0]):
                row = zf_in[r, :]
                valid = np.isfinite(row)
                if not np.any(valid):
                    zf_in[r, :] = 0.0
                elif np.count_nonzero(valid) < row.size:
                    fill = np.nanmean(row[valid])
                    row = row.copy()
                    row[~valid] = fill
                    zf_in[r, :] = row
        else:
            for c in range(zf_in.shape[1]):
                col = zf_in[:, c]
                valid = np.isfinite(col)
                if not np.any(valid):
                    zf_in[:, c] = 0.0
                elif np.count_nonzero(valid) < col.size:
                    fill = np.nanmean(col[valid])
                    col = col.copy()
                    col[~valid] = fill
                    zf_in[:, c] = col

        n = zf_in.shape[fft_axis]
        if n < 2:
            return x, z

        remove_dc = bool(getcfg('main', 'pyqtgraph', 'fft_remove_dc', default=True))
        detrend_linear = bool(getcfg('main', 'pyqtgraph', 'fft_detrend_linear', default=True))
        apply_window = bool(getcfg('main', 'pyqtgraph', 'fft_apply_hann_window', default=True))
        drop_zero = bool(getcfg('main', 'pyqtgraph', 'fft_drop_zero_bin', default=True))
        drop_low_bins = int(getcfg('main', 'pyqtgraph', 'fft_drop_low_bins', default=2))

        zf_work = np.asarray(zf_in, dtype=float)
        if remove_dc:
            zf_work = zf_work - np.mean(zf_work, axis=fft_axis, keepdims=True)
        if detrend_linear and n > 1:
            idx = np.arange(n, dtype=float)
            if fft_axis == 1:
                for r in range(zf_work.shape[0]):
                    row = zf_work[r, :]
                    slope = (row[-1] - row[0]) / float(n - 1)
                    zf_work[r, :] = row - (row[0] + slope * idx)
            else:
                for c in range(zf_work.shape[1]):
                    col = zf_work[:, c]
                    slope = (col[-1] - col[0]) / float(n - 1)
                    zf_work[:, c] = col - (col[0] + slope * idx)
        if apply_window and n > 1:
            win = np.hanning(n)
            shape = [1] * zf_work.ndim
            shape[fft_axis] = n
            zf_work = zf_work * win.reshape(shape)

        zf = np.fft.rfft(zf_work, axis=fft_axis)
        xf = np.fft.rfftfreq(n, d=abs(dx))
        if drop_zero and xf.size > 1:
            slicer = [slice(None)] * zf.ndim
            slicer[fft_axis] = slice(1, None)
            zf = zf[tuple(slicer)]
            xf = xf[1:]
        if drop_low_bins > 0 and xf.size > drop_low_bins:
            slicer = [slice(None)] * zf.ndim
            slicer[fft_axis] = slice(drop_low_bins, None)
            zf = zf[tuple(slicer)]
            xf = xf[drop_low_bins:]
        if x.ndim == 2:
            if fft_axis == 1:
                x_out = np.tile(xf, (zf.shape[0], 1))
            else:
                x_out = np.tile(xf.reshape(-1, 1), (1, zf.shape[1]))
        else:
            x_out = xf
        return x_out, np.abs(zf)

    def _fft2d_axis_y(self, y: np.ndarray, z: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        if z.ndim != 2 or max(z.shape) < 2:
            return y, z

        zf_in = np.asarray(z, dtype=float)
        fft_axis = 0
        if y.ndim == 2 and y.shape == z.shape:
            with np.errstate(invalid='ignore'):
                dy0 = np.nanmedian(np.abs(np.diff(y, axis=0)))
                dy1 = np.nanmedian(np.abs(np.diff(y, axis=1)))
            if np.isfinite(dy0) and (not np.isfinite(dy1) or dy0 >= dy1):
                fft_axis = 0
                y_axis = np.nanmedian(y, axis=1)
            else:
                fft_axis = 1
                y_axis = np.nanmedian(y, axis=0)
        elif y.ndim == 1 and y.size == z.shape[0]:
            fft_axis = 0
            y_axis = y
        elif y.ndim == 1 and y.size == z.shape[1]:
            fft_axis = 1
            y_axis = y
        else:
            return y, z

        finite_coord = np.isfinite(y_axis)
        if np.count_nonzero(finite_coord) < 2:
            return y, z
        y_axis = y_axis[finite_coord]
        if fft_axis == 0:
            zf_in = zf_in[finite_coord, :]
        else:
            zf_in = zf_in[:, finite_coord]

        sort_idx = np.argsort(y_axis)
        y_axis = y_axis[sort_idx]
        if fft_axis == 0:
            zf_in = zf_in[sort_idx, :]
        else:
            zf_in = zf_in[:, sort_idx]
        diffs = np.diff(y_axis)
        diffs = diffs[np.isfinite(diffs) & (diffs != 0)]
        if diffs.size == 0:
            return y, z
        dy = float(np.median(np.abs(diffs)))
        if dy == 0:
            return y, z

        if fft_axis == 0:
            for c in range(zf_in.shape[1]):
                col = zf_in[:, c]
                valid = np.isfinite(col)
                if not np.any(valid):
                    zf_in[:, c] = 0.0
                elif np.count_nonzero(valid) < col.size:
                    fill = np.nanmean(col[valid])
                    col = col.copy()
                    col[~valid] = fill
                    zf_in[:, c] = col
        else:
            for r in range(zf_in.shape[0]):
                row = zf_in[r, :]
                valid = np.isfinite(row)
                if not np.any(valid):
                    zf_in[r, :] = 0.0
                elif np.count_nonzero(valid) < row.size:
                    fill = np.nanmean(row[valid])
                    row = row.copy()
                    row[~valid] = fill
                    zf_in[r, :] = row

        n = zf_in.shape[fft_axis]
        if n < 2:
            return y, z

        remove_dc = bool(getcfg('main', 'pyqtgraph', 'fft_remove_dc', default=True))
        detrend_linear = bool(getcfg('main', 'pyqtgraph', 'fft_detrend_linear', default=True))
        apply_window = bool(getcfg('main', 'pyqtgraph', 'fft_apply_hann_window', default=True))
        drop_zero = bool(getcfg('main', 'pyqtgraph', 'fft_drop_zero_bin', default=True))
        drop_low_bins = int(getcfg('main', 'pyqtgraph', 'fft_drop_low_bins', default=2))

        zf_work = np.asarray(zf_in, dtype=float)
        if remove_dc:
            zf_work = zf_work - np.mean(zf_work, axis=fft_axis, keepdims=True)
        if detrend_linear and n > 1:
            idx = np.arange(n, dtype=float)
            if fft_axis == 0:
                for c in range(zf_work.shape[1]):
                    col = zf_work[:, c]
                    slope = (col[-1] - col[0]) / float(n - 1)
                    zf_work[:, c] = col - (col[0] + slope * idx)
            else:
                for r in range(zf_work.shape[0]):
                    row = zf_work[r, :]
                    slope = (row[-1] - row[0]) / float(n - 1)
                    zf_work[r, :] = row - (row[0] + slope * idx)
        if apply_window and n > 1:
            win = np.hanning(n)
            shape = [1] * zf_work.ndim
            shape[fft_axis] = n
            zf_work = zf_work * win.reshape(shape)

        zf = np.fft.rfft(zf_work, axis=fft_axis)
        yf = np.fft.rfftfreq(n, d=abs(dy))
        if drop_zero and yf.size > 1:
            slicer = [slice(None)] * zf.ndim
            slicer[fft_axis] = slice(1, None)
            zf = zf[tuple(slicer)]
            yf = yf[1:]
        if drop_low_bins > 0 and yf.size > drop_low_bins:
            slicer = [slice(None)] * zf.ndim
            slicer[fft_axis] = slice(drop_low_bins, None)
            zf = zf[tuple(slicer)]
            yf = yf[drop_low_bins:]
        if y.ndim == 2:
            if fft_axis == 0:
                y_out = np.tile(yf.reshape(-1, 1), (1, zf.shape[1]))
            else:
                y_out = np.tile(yf, (zf.shape[0], 1))
        else:
            y_out = yf
        return y_out, np.abs(zf)

    def _fft_scatter2d(self, x: np.ndarray, y: np.ndarray, z: np.ndarray, axis: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        # Compute FFT trace-by-trace for scattered 2D data by grouping points
        # along the non-transformed axis with tolerance clustering.
        # This is resilient to small floating-point jitter in nominally gridded sweeps.
        x_flat = np.asarray(x, dtype=float).flatten()
        y_flat = np.asarray(y, dtype=float).flatten()
        z_flat = np.asarray(z, dtype=float).flatten()

        valid = np.isfinite(x_flat) & np.isfinite(y_flat) & np.isfinite(z_flat)
        if not np.any(valid):
            return np.array([]), np.array([]), np.array([])

        x_flat = x_flat[valid]
        y_flat = y_flat[valid]
        z_flat = z_flat[valid]

        grp_axis = y_flat if axis == 'x' else x_flat
        fft_axis = x_flat if axis == 'x' else y_flat

        def _cluster_axis(vals: np.ndarray) -> np.ndarray:
            v = np.asarray(vals, dtype=float)
            if v.size == 0:
                return v
            uv = np.unique(v)
            if uv.size <= 1:
                return np.zeros(v.size, dtype=int)
            diffs = np.diff(np.sort(uv))
            diffs = diffs[np.isfinite(diffs) & (diffs > 0)]
            if diffs.size > 0:
                step = float(np.median(diffs))
                tol = max(step * 0.25, 1e-15)
            else:
                span = float(np.nanmax(v) - np.nanmin(v)) if np.isfinite(v).any() else 1.0
                tol = max(span * 1e-9, 1e-15)
            v0 = float(np.nanmin(v))
            return np.rint((v - v0) / tol).astype(int)

        grp_bins = _cluster_axis(grp_axis)
        unique_groups = np.unique(grp_bins)

        x_out: List[np.ndarray] = []
        y_out: List[np.ndarray] = []
        z_out: List[np.ndarray] = []

        for g in unique_groups:
            mask = grp_bins == g
            if np.count_nonzero(mask) < 2:
                continue

            ax = fft_axis[mask]
            zv = z_flat[mask]
            order = np.argsort(ax)
            ax = ax[order]
            zv = zv[order]

            diffs = np.diff(ax)
            diffs = diffs[np.isfinite(diffs) & (diffs != 0)]
            if diffs.size == 0:
                continue

            d = float(np.median(np.abs(diffs)))
            if d == 0:
                continue

            f, zf_amp = self._fft_positive_frequency(zv, d)
            if f.size == 0:
                continue

            if axis == 'x':
                x_out.append(f)
                y_out.append(np.full(f.shape, float(np.median(grp_axis[mask]))))
            else:
                x_out.append(np.full(f.shape, float(np.median(grp_axis[mask]))))
                y_out.append(f)
            z_out.append(zf_amp)

        if len(z_out) == 0:
            return x_flat, y_flat, z_flat

        return np.concatenate(x_out), np.concatenate(y_out), np.concatenate(z_out)


class AutoPlot(PlotWidget):
    """Widget for automatic plotting with pyqtgraph.

    Uses :class:`.FigureMaker` to produce subplots.
    """

    def __init__(self, parent: Optional[PlotWidgetContainer]) -> None:
        """Constructor for the pyqtgraph auto plot widget.

        :param parent: plot widget container
        """
        super().__init__(parent=parent)

        self.fmWidget: Optional[FigureWidget] = None
        self.figConfig: Optional[FigureConfigToolBar] = None
        self.figOptions: FigureOptions = FigureOptions()
        self.title : Optional[str] = None
        self._cursorConnectionCount = 0

        layout = QtWidgets.QVBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        self.setLayout(layout)
        self.setMinimumSize(*getcfg('main', 'pyqtgraph', 'minimum_plot_size',
                                    default=(400, 400)))

    def setData(self, data: Optional[DataDictBase]) -> None:
        """Uses :class:`.FigureMaker` to populate the plot(s).

        This method aims to re-use existing plotwidgets if possible -- i.e.,
        when the type of data (generally speaking) has not changed.
        If changes to the data structure are detected, then all subplot
        widgets are re-created from scratch, however.

        :param data: input data
        :return: ``None``
        """
        super().setData(data)
        if self.data is None:
            return

        fmKwargs = {}  # {'widget': self.fmWidget}
        dc = self.dataChanges
        if not dc['dataTypeChanged'] and not dc['dataStructureChanged']:
            fmKwargs['clearWidget'] = False
        else:
            fmKwargs['clearWidget'] = True
        self._plotData(**fmKwargs)

    def _plotData(self, **kwargs: Any) -> None:
        if self.data is None:
            return

        with FigureMaker(parentWidget=self, widget=self.fmWidget,
                         **kwargs) as fm:

            fm.complexRepresentation = self.figOptions.complexRepresentation
            fm.combineTraces = self.figOptions.combineLinePlots
            fm.colormap = self.figOptions.colormap
            fm.logX = self.figOptions.logX
            fm.logY = self.figOptions.logY
            fm.logColor = self.figOptions.logColor
            fm.fftAxis = self.figOptions.fftAxis

            for dep in self.data.dependents():
                inds = self.data.axes(dep)
                dvals = self.data.data_vals(dep)
                pdt = determinePlotDataType(self.data.extract([dep]))
                plotId = fm.addData(
                    *[np.asanyarray(self.data.data_vals(n)) for n in inds] + [dvals],
                    labels=[str(self.data.label(n)) for n in inds] + [str(self.data.label(dep))],
                    plotDataType=pdt,
                )

        if self.fmWidget is None:
            self.fmWidget = fm.widget
            self.layout().addWidget(self.fmWidget)
            self.figConfig = FigureConfigToolBar(self.figOptions,
                                                 parent=self)
            self.layout().addWidget(self.figConfig)
            self.figConfig.optionsChanged.connect(self._refreshPlot)
            self.figConfig.figCopied.connect(self.onfigCopied)
            self.figConfig.figSaved.connect(self.onfigSaved)

        if self.data.has_meta('title'):
            self.fmWidget.setTitle(self.data.meta_val('title'))
            self.title = self.data.meta_val('title')

        #update FigOptions numAxes and imagData
        self.figOptions.numAxes = len(inds)

        #define imagData for single and multiple value data
        for val in dvals:
            try:
                if not all(val.imag == 0):
                    self.figOptions.imagData = True
                    break
            except:
                 if not val.imag == 0:
                    self.figOptions.imagData = True
                    break

        #Assertions to make mypy happy
        assert self.figConfig is not None
        assert self.figConfig.updateComplexButton() is not None

        self.figConfig.updateComplexButton()
        self._connectCursorSignals()

    def _connectCursorSignals(self) -> None:
        if self.fmWidget is None:
            return
        for plot_widget in self.fmWidget.subPlots:
            if getattr(plot_widget, '_cursor_connected', False):
                continue
            plot_widget.cursorPositionChanged.connect(self._onCursorMoved)
            setattr(plot_widget, '_cursor_connected', True)

    @Slot(object, float, float, object)
    def _onCursorMoved(self, plot_widget: PlotBase, x: float, y: float, z: Optional[float]) -> None:
        if self.figConfig is None:
            return

        x_axis = plot_widget.plot.getAxis('bottom')
        y_axis = plot_widget.plot.getAxis('left')
        x_name = x_axis.labelText or 'x'
        y_name = y_axis.labelText or 'y'
        x_unit = x_axis.labelUnits or ''
        y_unit = y_axis.labelUnits or ''

        x_suffix = f' {x_unit}' if x_unit else ''
        y_suffix = f' {y_unit}' if y_unit else ''
        text = f'{x_name}: {x:.6g}{x_suffix}   {y_name}: {y:.6g}{y_suffix}'

        if isinstance(plot_widget, PlotWithColorbar):
            z_name = 'z'
            z_unit = ''
            try:
                z_name = plot_widget.colorbar.axis.labelText or 'z'
                z_unit = plot_widget.colorbar.axis.labelUnits or ''
            except Exception:
                pass

            if z is not None and np.isfinite(z):
                z_suffix = f' {z_unit}' if z_unit else ''
                text += f'   {z_name}: {z:.6g}{z_suffix}'
            else:
                text += f'   {z_name}: -'

        self.figConfig.setCursorText(text)

    @Slot()
    def _refreshPlot(self) -> None:
        self._plotData()

    @Slot()
    def onfigCopied(self) -> None:
        """
        Gets triggered when figCopied signal is emitted from self.figConfig
        Copy the current figuremaker widget to the clipboard.
        """
        assert isinstance(self.fmWidget, FigureWidget)
        screenshot = self.fmWidget.grab(rectangle=QtCore.QRect(QtCore.QPoint(0, 0), QtCore.QSize(-1, -1)))
        clipboard = QtWidgets.QApplication.clipboard()
        clipboard.setImage(screenshot.toImage())

    @Slot()
    def onfigSaved(self) -> None:
        """
        Gets triggered when figSaved signal is emitted from self.figConfig
        Save the current figuremaker widget to the data directory as a png
        with a timestamp at the front.
        """
        assert isinstance(self.fmWidget, FigureWidget)
        assert isinstance(self.data, DataDictBase)
        screenshot = self.fmWidget.grab(rectangle=QtCore.QRect(QtCore.QPoint(0, 0), QtCore.QSize(-1, -1)))
        if self.title is not None:
            path = Path(self.title)
            # add a timestamp here
            t = time.localtime()
            time_str = time.strftime(TIMESTRFORMAT, t)
            filename = time_str+'_'+str(path.stem)+'.png'
            screenshot.save(str(path.parent)+'/'+filename, format='PNG')
            return

        logger.error("Could not find the path of the figure. Figure has not been saved")

    # TODO: Allow for the option to choose filetypes and the name/directory


@dataclass
class FigureOptions:
    """Dataclass that describes the configuration options for the figure."""

    #: whether to plot all 1D traces into a single panel
    combineLinePlots: bool = False

    #: how to represent complex data
    complexRepresentation: ComplexRepresentation = ComplexRepresentation.realAndImag

    #: The number of independent axes that are passed
    numAxes: int = 0

    #: whether the dependent data contains any instance of imaginary data
    imagData: bool = False

    #: colormap used for 2D plots
    colormap: str = 'magma_r'

    #: logarithmic axis scaling options
    logX: bool = False
    logY: bool = False
    logColor: bool = False

    #: FFT axis transform: 'none', 'x', or 'y'
    fftAxis: str = 'none'


class FigureConfigToolBar(QtWidgets.QToolBar):
    """Simple toolbar to configure the figure."""

    # TODO: find better config system that generates GUI automatically and
    #   links updates easier.

    #: Signal() -- emitted when options have been changed in the GUI.
    optionsChanged = Signal()
    #: Signal() -- emitted when the copy figure button has been pressed
    figCopied = Signal()
    #: Signal() -- emitted when the save figure button has been pressed
    figSaved = Signal()

    def __init__(self, options: FigureOptions,
                 parent: Optional[QtWidgets.QWidget] = None) -> None:
        """Constructor.

        :param options: options object. GUI interaction will make changes
            in-place to this object.
        :param parent: parent Widget
        """
        super().__init__(parent)

        self.options = options
        self._complexWidgetAction: Optional[QtWidgets.QAction] = None

        combineLinePlots = self.addAction("Combine 1D")
        combineLinePlots.setCheckable(True)
        combineLinePlots.setChecked(self.options.combineLinePlots)
        combineLinePlots.triggered.connect(
            lambda: self._setOption('combineLinePlots',
                                    combineLinePlots.isChecked())
        )

        self.addSeparator()

        self.colormapSelector = QtWidgets.QComboBox(parent=self)
        self.colormapSelector.setToolTip('Select colormap for 2D plots')
        cmaps = getcfg('main', 'pyqtgraph', 'colormap_options', default=[
            'magma_r', 'magma', 'viridis', 'inferno', 'plasma',
            'cividis', 'turbo', 'CET-L1', 'CET-L9'
        ])
        self.colormapSelector.addItems(cmaps)
        if self.options.colormap in cmaps:
            self.colormapSelector.setCurrentText(self.options.colormap)
        self.colormapSelector.currentTextChanged.connect(
            lambda text: self._setOption('colormap', text)
        )
        self.addWidget(self.colormapSelector)

        self.logXAction = self.addAction('Log X')
        self.logXAction.setCheckable(True)
        self.logXAction.setChecked(self.options.logX)
        self.logXAction.triggered.connect(
            lambda: self._setOption('logX', self.logXAction.isChecked())
        )

        self.logYAction = self.addAction('Log Y')
        self.logYAction.setCheckable(True)
        self.logYAction.setChecked(self.options.logY)
        self.logYAction.triggered.connect(
            lambda: self._setOption('logY', self.logYAction.isChecked())
        )

        self.logColorAction = self.addAction('Log Color')
        self.logColorAction.setCheckable(True)
        self.logColorAction.setChecked(self.options.logColor)
        self.logColorAction.triggered.connect(
            lambda: self._setOption('logColor', self.logColorAction.isChecked())
        )

        fftOptions = QtWidgets.QMenu(parent=self)
        fftGroup = QtWidgets.QActionGroup(fftOptions)
        fftGroup.setExclusive(True)
        for text, val in [('FFT: none', 'none'), ('FFT: X axis', 'x'), ('FFT: Y axis', 'y')]:
            act = QtWidgets.QAction(text, fftOptions)
            act.setCheckable(True)
            act.setData(val)
            act.setChecked(self.options.fftAxis == val)
            fftGroup.addAction(act)
            fftOptions.addAction(act)

        fftGroup.triggered.connect(
            lambda a: self._setOption('fftAxis', str(a.data()))
        )

        self.fftButton = QtWidgets.QToolButton()
        self.fftButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.fftButton.setText('FFT')
        self.fftButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.fftButton.setMenu(fftOptions)
        self.addWidget(self.fftButton)

        complexOptions = QtWidgets.QMenu(parent=self)
        complexGroup = QtWidgets.QActionGroup(complexOptions)
        complexGroup.setExclusive(True)
        self._createComplexRepresentation()
        
        # Adding functionality to copy and save the graph
        self.copyFig = self.addAction('Copy Figure', self._copyFig)
        self.saveFig = self.addAction('Save Figure', self._saveFig)

        spacer = QtWidgets.QWidget(parent=self)
        spacer.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        self.addWidget(spacer)

        self.cursorLabel = QtWidgets.QLabel('x: -, y: -, z: -', parent=self)
        self.cursorLabel.setMinimumWidth(380)
        self.cursorLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.addWidget(self.cursorLabel)


    def _setOption(self, option: str, value: Any) -> None:
        setattr(self.options, option, value)
        self.optionsChanged.emit()
        
    def _copyFig(self) -> None:
        self.figCopied.emit()

    def _saveFig(self) -> None:
        self.figSaved.emit()

    def _createComplexRepresentation(self) -> bool:
        #constructs/reconstructs the Complex Button with different viewing options based upon input data

        complexOptions = QtWidgets.QMenu(parent=self)
        complexGroup = QtWidgets.QActionGroup(complexOptions)
        complexGroup.setExclusive(True)

        for k in ComplexRepresentation:

            #Checks instance of non-imaginary data (to only enable real view) and 2 independent variables (to disable logMag view)
            if not self.options.imagData and not k == ComplexRepresentation.real: continue
            if self.options.numAxes == 2 and k == ComplexRepresentation.log_MagAndPhase: continue

            a = QtWidgets.QAction(k.label, complexOptions)
            a.setCheckable(True)
            complexGroup.addAction(a)
            complexOptions.addAction(a)
            a.setChecked(k == self.options.complexRepresentation)
        complexGroup.triggered.connect(
            lambda _a: self._setOption('complexRepresentation',
                                       ComplexRepresentation.fromLabel(_a.text()))
        )
        complexButton = QtWidgets.QToolButton()
        complexButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        complexButton.setText('Complex')
        complexButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        complexButton.setMenu(complexOptions)

        self._complexWidgetAction = self.addWidget(complexButton)
        return True

    def updateComplexButton(self) -> bool:
        if self._complexWidgetAction is not None:
            self.removeAction(self._complexWidgetAction)
            self._complexWidgetAction = None
        self._createComplexRepresentation()
        return True

    def setCursorText(self, text: str) -> None:
        self.cursorLabel.setText(text)